### ISSUE TITLE
Banner aspect on small/large screens is squished

### ISSUE THREAD

**Issue by zachbryant** [Purdue-CSUSB/purdueusb.com#42]
![image](https://user-images.githubusercontent.com/32501288/88975871-e3024100-d26f-11ea-9614-e16edc4cfcbd.png)
On Safari mobile

![image](https://user-images.githubusercontent.com/32501288/88975932-03320000-d270-11ea-9087-f42490d12921.png)
On Chrome laptop

**Comment by nalderto** [comment]
This appears to be resolved.  I am not able to reproduce.
